### ISSUE TITLE
Wrong number of sponsored-promoted products

### ISSUE THREAD

**Issue by gtopsis** [keybraker/skroutz-sponsored-flagger#3]
## Description
There is a case in which both the extension's popup and the relative filter show a wrong number of the counted sponsored/promoted products.
More specifically, if the number of those products are equal to `n` then the above relative counters are equal to `k x n`, where `k = 2, 4, 8, .... `

## How to reproduce
- visit https://www.skroutz.gr/c/1105/tablet.html?o=tablet
- toggle the visibility of sponsored/promoted products
- navigate to the second (or any different) page of results
- toggle again the visibility of sponsored/promoted products
- return to the first page of results
- toggle again the visibility of sponsored/promoted products
- check both the filter and the popup elements of the extension

## Expected behavior
Well, it depends on the desired functionality. Some logical behaviors would be the following.
- Counters represents the number of sponsored products per page of results (recommended)
- Counters represent the **total number** of products that a visitor has found so far during his/her navigation

In the screenshot below, I would expect the counter to remain 4.

## Screenshot
![Screenshot from 2023-04-09 10-28-03](https://user-images.githubusercontent.com/11655698/230770212-b33def97-8d9f-4b62-8540-74f45df72d42.png)

## Environment
- Chrome 112.0
- Ubuntu 22.10

**Comment by keybraker** [comment]
Will be fixed on release 1.3
