### ISSUE TITLE
Counter of the Filter element does not indicate the right number of sponsored on the current page

### ISSUE THREAD

**Issue by gtopsis** [keybraker/skroutz-sponsored-flagger#4]
**Note:** This issue relates to the current version of code (14/04/2023)

## Description
There is a case in which the extension's Filter element show a wrong number of the counted sponsored products.
More specifically, if you visit a page of results different from the first, then you will notice that the number of the sponsored products in the Filter element has not been updated accordingly.

## How to reproduce
- visit https://www.skroutz.gr/c/1105/tablet.html?o=tablet
- visit the 2nd page of results
- check the counter of the Filter element

## Expected behavior
The number/counter of the Filter element should indicate the actual number of sponsored products in the current page. 

In the screenshots below, I would expect the counter to be 0 on the second screenshot.

### First page of results

![Screenshot from 2023-04-14 22-40-09](https://user-images.githubusercontent.com/11655698/232141518-c2fc47db-c69b-411b-929d-28b9523e77b2.png)

### Second page of results

![Screenshot from 2023-04-14 22-40-26](https://user-images.githubusercontent.com/11655698/232141662-3e92c5f6-560b-4296-b870-d7509d07d109.png)

## Environment
- Chrome 112.0
- Ubuntu 22.10

**Comment by keybraker** [comment]
Will be fixed on version 1.4
