### ISSUE TITLE
Sponsored shelf not counted on the popup since the commit #ef6ab95

### ISSUE THREAD

**Issue by bandisast** [keybraker/skroutz-sponsored-flagger#6]
Issue: 
![image](https://user-images.githubusercontent.com/68644945/233560591-d4ce45d7-4ab2-4183-b561-cca32110edcc.png)

While the sponsored shelf *does* exist, it doesn't appear to get counted on the popup file. Until the previous commit on the main repo, this used to work. Tested both on Chrome and Firefox, on a Windows 11 computer.

It was counted normally both on Chrome and Firefox until the above commit, so there must be a breaking change there.

**Comment by keybraker** [comment]
Great catch, will take a look at the diff to see what got changed.
